
public class SettingData{
    // Agent Status
    public int      Agent_HealthPoint;
    public int      Agent_AttackPoint;
    public float    Agent_MoveSpeed;
    public float    Agent_RotateSpeed;
    public float    Agent_FireRate;
    public int      Agent_MagazineSize;
    public float    Agent_ViewDistance;
    // Spawn Rate
    public int      SpawnRate_Zombie;
    public int      SpawnRate_Tank;
    public int      SpawnRate_Spitter;
    public int      SpawnRate_Charger;
    public int      SpawnRate_Wanderer;
    // Zombie Status
    public int      Zombie_HealthPoint;
    public int      Zombie_AttackPoint;
    public float    Zombie_MoveSpeed;
    public float    Zombie_RotateSpeed;
    // Wander Status
    public int      Wanderer_HealthPoint;
    public int      Wanderer_AttackPoint;
    public float    Wanderer_MoveSpeed;
    public float    Wanderer_RotateSpeed;
    public float    Wanderer_ViewDistance;
    // Tank Status
    public int      Tank_HealthPoint;
    public int      Tank_AttackPoint;
    public float    Tank_MoveSpeed;
    public float    Tank_RotateSpeed;
    public float    Tank_ViewDistance;
    // Spitter Status
    public int      Spitter_HealthPoint;
    public int      Spitter_AttackPoint;
    public float    Spitter_MoveSpeed;
    public float    Spitter_RotateSpeed;
    public float    Spitter_FireRate;
    public float    Spitter_ViewDistance;
    // Charger Status
    public int      Charger_HealthPoint;
    public int      Charger_AttackPoint;
    public float    Charger_MoveSpeed;
    public float    Charger_RotateSpeed;
    public float    Charger_ChargeSpeed;
    public float    Charger_FireRate;
    public float    Charger_ViewDistance;
}
